version: '3'
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
          - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      myNetwork:
        aliases:
          - mongo

  webapp:
    image: webapp
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_DATABASE=mydb
    deploy:
      replicas: 3
    networks: 
      - myNetwork

networks:
  myNetwork:
    driver: overlay
